{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "keycloak-cr-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "metrics-monitor" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - {{- if .Values.metrics.secure }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      {{- end }}
      path: /metrics
      port: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
      scheme: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
      {{- if .Values.metrics.secure }}
      tlsConfig:
        serverName: {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "metrics-service" "context" $) }}.{{ .Release.Namespace }}.svc
        {{- if .Values.certManager.enabled }}
        ca:
          secret:
            name: metrics-server-cert
            key: ca.crt
        cert:
          secret:
            name: metrics-server-cert
            key: tls.crt
        keySecret:
          name: metrics-server-cert
          key: tls.key
        insecureSkipVerify: false
        {{- else }}
        insecureSkipVerify: true
        {{- end }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "keycloak-cr-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
{{- end }}
