{{- if and .Values.certManager.enable .Values.metrics.enable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "keycloak-cr-operator.labels" . | nindent 4 }}
  name: {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "metrics-certs" "context" $) }}
  namespace: {{ include "keycloak-cr-operator.namespaceName" . | quote }}
spec:
  dnsNames:
  - {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}.{{ include "keycloak-cr-operator.namespaceName" $ }}.svc
  - {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}.{{ include "keycloak-cr-operator.namespaceName" $ }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "selfsigned-issuer" "context" $) }}
  secretName: metrics-server-cert
{{- end }}
