resources:
- manager.yaml
secretGenerator:
- literals:
  - keycloak-admin-username=admin
  - keycloak-admin-password=secret
  name: keycloak-cr-operator
configMapGenerator:
- literals:
  - KEYCLOAK_URL=http://keycloak.keycloak.svc.cluster.local
  name: keycloak-cr-operator
