resources:
- manager.yaml
secretGenerator:
- literals:
  - keycloak-admin-username=admin
  - keycloak-admin-password=secret
  name: keycloak-cr-operator
configMapGenerator:
- literals:
  - KEYCLOAK_URL=http://keycloak.keycloak.svc.cluster.local
  name: keycloak-cr-operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: example.com/keycloak-cr-operator
  newTag: v0.0.1
