{{- if and .Values.hooks.enabled .Values.webhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- include "keycloak-cr-operator.labels" . | nindent 4 }}
  name: {{ printf "%s-hooks" (include "keycloak-cr-operator.serviceAccountName" .) }}
  namespace: {{ .Release.Namespace }}
{{- end }}
