---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-cr-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - keycloak.osc.edu
  resources:
  - keycloakclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.osc.edu
  resources:
  - keycloakclients/finalizers
  verbs:
  - update
- apiGroups:
  - keycloak.osc.edu
  resources:
  - keycloakclients/status
  verbs:
  - get
  - patch
  - update
