apiVersion: keycloak.osc.edu/v1alpha1
kind: KeycloakClient
metadata:
  labels:
    app.kubernetes.io/name: keycloak-cr-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakclient-test
  namespace: default
spec:
  clientID: kubernetes-default-keycloakclient-test
  realm: master
  clientSecretRef:
    name: keycloak-test
    key: client-secret
    create: true
  redirectUris:
    - https://example.com/*
    - https://example.test.com/*
  defaultClientScopes:
    - web-origins
    - profile
    - email
  configMapName: keycloak-config
