apiVersion: keycloak.osc.edu/v1alpha1
kind: KeycloakClient
metadata:
  labels:
    app.kubernetes.io/name: keycloak-cr-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakclient-sample
spec:
  clientID: kubernetes-keycloakclient-sample
  realm: master
  clientSecretRef:
    name: keycloak-sample
    key: client-secret
    create: false
  redirectUris:
    - https://example.com/*
    - https://example.test.com/*
  defaultClientScopes:
    - web-origins
    - profile
    - email
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: keycloak-cr-operator
    app.kubernetes.io/managed-by: kustomize
    keycloak.osc.edu/keycloakclient: keycloakclient-sample
  name: keycloak-sample
data:
  client-secret: c2FtcGxlLXNlY3JldA==
