{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "keycloak-cr-operator.labels" . | nindent 4 }}
  name: {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "imagepullsecret" "context" $) }}
  namespace: {{ include "keycloak-cr-operator.namespaceName" . | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "keycloak-cr-operator.imagePullSecret" . }}
{{- end }}
