apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "keycloak-cr-operator.labels" . | nindent 4 }}
  name: {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "manager-secret" "context" $) }}
  namespace: {{ include "keycloak-cr-operator.namespaceName" . | quote }}
data:
  KEYCLOAK_ADMIN_USERNAME: {{ required "Admin username is required" (tpl .Values.manager.config.adminUsername .) | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ required "Admin password is required" (tpl .Values.manager.config.adminPassword .) | b64enc | quote }}
