apiVersion: v2
name: keycloak-cr-operator
description: A Helm chart to distribute keycloak-cr-operator
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: treydock
keywords:
  - keycloak
  - kubernetes
  - operator
annotations:
  kubebuilder.io/generated-by: kubebuilder
