apiVersion: v2
name: keycloak-cr-operator
description: A Helm chart to distribute keycloak-cr-operator
type: application
version: v0.0.3
appVersion: v0.0.3
maintainers:
  - name: treydock
keywords:
  - keycloak
  - kubernetes
  - operator
annotations:
  kubebuilder.io/generated-by: kubebuilder
