{{- if ne .Values.serviceAccount.enabled false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "keycloak-cr-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "keycloak-cr-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
