{{- if or (not (hasKey .Values.manager "enabled")) (.Values.manager.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "keycloak-cr-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
    {{- with .Values.manager.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "manager" "context" $) }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.manager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.manager.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      {{- include "keycloak-cr-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        checksum/secret: {{ (include (print $.Template.BasePath "/extras/manager-secret.yaml") . | sha256sum) }}
        checksum/config: {{ (include (print $.Template.BasePath "/extras/manager-configmap.yaml") . | sha256sum) }}
      {{- with .Values.manager.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keycloak-cr-operator.labels" . | nindent 8 }}
        control-plane: controller-manager
    spec:
      {{- with .Values.manager.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.manager.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.manager.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.global.imagePullSecrets | default .Values.manager.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args:
        {{- if .Values.metrics.enabled }}
        - --metrics-bind-address=:{{ .Values.metrics.port }}
        {{- if not .Values.metrics.secure }}
        - --metrics-secure=false
        {{- end }}
        {{- else }}
        # Bind to :0 to disable the controller-runtime managed metrics server
        - --metrics-bind-address=0
        {{- end }}
        - --health-probe-bind-address=:{{ .Values.manager.healthPort }}
        {{- range .Values.manager.args }}
        - {{ . }}
        {{- end }}
        {{- range .Values.manager.extraArgs }}
        - {{ . }}
        {{- end }}
        {{- if and .Values.certManager.enabled .Values.metrics.enabled .Values.metrics.secure }}
        - --metrics-cert-path=/tmp/k8s-metrics-server/metrics-certs
        {{- end }}
        {{- if .Values.certManager.enabled }}
        - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
        {{- end }}
        command:
        - /manager
        envFrom:
        - secretRef:
            name: {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "manager-secret" "context" $) }}
        - configMapRef:
            name: {{ include "keycloak-cr-operator.resourceName" (dict "suffix" "manager-config" "context" $) }}
        {{- with .Values.manager.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.manager.healthPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: {{ .Values.manager.healthPort }}
          name: health
          protocol: TCP
        - containerPort: {{ .Values.webhook.port }}
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.manager.healthPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- if .Values.manager.resources }}
          {{- toYaml .Values.manager.resources | nindent 10 }}
          {{- else }}
          {}
          {{- end }}
        securityContext:
          {{- if .Values.manager.securityContext }}
          {{- toYaml .Values.manager.securityContext | nindent 10 }}
          {{- else }}
          {}
          {{- end }}
        volumeMounts:
          {{- if .Values.manager.extraVolumeMounts }}
          {{- toYaml .Values.manager.extraVolumeMounts | nindent 10 }}
          {{- end }}
          {{- if and .Values.certManager.enabled .Values.metrics.enabled .Values.metrics.secure }}
          - mountPath: /tmp/k8s-metrics-server/metrics-certs
            name: metrics-certs
            readOnly: true
          {{- end }}
          {{- if .Values.certManager.enabled }}
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: webhook-certs
            readOnly: true
          {{- end }}
      securityContext:
        {{- if .Values.manager.podSecurityContext }}
        {{- toYaml .Values.manager.podSecurityContext | nindent 8 }}
        {{- else }}
        {}
        {{- end }}
      serviceAccountName: {{ include "keycloak-cr-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.manager.terminationGracePeriodSeconds }}
      volumes:
        {{- if .Values.manager.extraVolumes }}
        {{- toYaml .Values.manager.extraVolumes | nindent 8 }}
        {{- end }}
        {{- if and .Values.certManager.enabled .Values.metrics.enabled .Values.metrics.secure }}
        - name: metrics-certs
          secret:
            items:
            - key: ca.crt
              path: ca.crt
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
            optional: false
            secretName: metrics-server-cert
        {{- end }}
        {{- if .Values.certManager.enabled }}
        - name: webhook-certs
          secret:
            secretName: webhook-server-cert
        {{- end }}
{{- end }}
