---
manager:
  image:
    tag: latest
  config:
    keycloakURL: http://keycloak.keycloak.svc.cluster.local
    adminUsername: admin
    adminPassword: secret
    adminRealm: master
    defaultRealm: master
    allowedRealms:
      - master
    clientIdPrefix: kubernetes
    clientIdRequired: '{{ .Config.ClientIDPrefix }}-{{ .Obj.Namespace }}-{{ .Obj.Name }}'
  env:
    - name: FOO
      value: bar
networkPolicy:
  allowMetricsFromPods: true
imagePullSecret:
  create: true
  registry: example.com
  username: username
  password: secret
